language: node_js
os:
    - linux
    - windows
    - osx
node_js:
    - "8.0.0"
    - "9.0.0"
    - "10.0.0"
    - "11.0.0"
    - "12.0.0"
sudo: false
script:
    - npm test
after_success:
    - npm run coverage